/**
 * Build identity — 0.2.0 dogfood issue 4.
 *
 * Exports the host-neutral build-info API: `packageVersion`, `gitCommit`, and
 * the current run-state `schemaVersion`. Package version is sourced from
 * package metadata (read at runtime — never runs git). The git commit is
 * stamped at BUILD time into a generated `build-info.json` shipped under
 * `dist/`; in a source/dev checkout (no build) it falls back to the
 * `PI_TASKFLOW_BUILD_COMMIT` env var, then to the deterministic string
 * `"unknown"`. **`git` is never invoked at runtime** (no `git rev-parse`, no
 * `.git` read) — the stamp is purely a build-time artifact.
 *
 * The build stamp lives under `dist/` (gitignored) so a normal build never
 * dirties the source tree. See `scripts/stamp-build-info.mjs`.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** The current run-state schema version. Bumped when the persisted `RunState`
 *  shape changes in a way a loader should be aware of. Optional metadata
 *  fields (packageVersion/gitCommit/host/parentRunId) were added in this
 *  version; absent fields on old runs are tolerated (backward compatible). */
export const CURRENT_RUN_STATE_SCHEMA_VERSION = 1;

/** The deterministic fallback when no build stamp is available (source/dev
 *  checkout, or a build that could not determine the commit). */
export const UNKNOWN_BUILD_COMMIT = "unknown";

export interface BuildInfo {
	/** Package version, sourced from the nearest package.json (runtime read). */
	packageVersion: string;
	/** Git commit the published dist was built from, stamped at build time.
	 *  `"unknown"` in a source/dev checkout (no `git` is ever run at runtime). */
	gitCommit: string;
	/** The current run-state schema version (see CURRENT_RUN_STATE_SCHEMA_VERSION). */
	schemaVersion: number;
	/** When the build stamp was generated (ms epoch), if known. */
	buildTime?: number;
}

let cachedPackageVersion: string | undefined;
let cachedStamp: { gitCommit?: string; buildTime?: number } | undefined;

/** Resolve the package version from the nearest package.json. Tries the
 *  taskflow-core package.json first, then walks up. Never throws — returns
 *  `"0.0.0"` if no version can be read. */
export function packageVersion(): string {
	if (cachedPackageVersion !== undefined) return cachedPackageVersion;
	const here = dirname(fileURLToPath(import.meta.url));
	// src/build-info.ts → ../package.json (taskflow-core). In dist, build-info.js
	// is at dist/build-info.js → ../package.json is still taskflow-core's.
	const candidates = [join(here, "..", "package.json"), join(here, "..", "..", "package.json")];
	for (const p of candidates) {
		try {
			const pkg: unknown = JSON.parse(readFileSync(p, "utf8"));
			if (pkg && typeof pkg === "object" && "version" in pkg) {
				const v = (pkg as { version?: unknown }).version;
				if (typeof v === "string" && v) {
					cachedPackageVersion = v;
					return v;
				}
			}
		} catch {
			/* try next candidate */
		}
	}
	cachedPackageVersion = "0.0.0";
	return cachedPackageVersion;
}

/** Read the build-time stamp (generated by scripts/stamp-build-info.mjs into
 *  dist/build-info.json). Returns `{}` when absent (source/dev checkout). */
function readBuildStamp(): { gitCommit?: string; buildTime?: number } {
	if (cachedStamp !== undefined) return cachedStamp;
	const here = dirname(fileURLToPath(import.meta.url));
	// In dist: build-info.js → ./build-info.json (sibling). In src: the stamp
	// is not generated (dev checkout) → readFileSync throws → {}.
	const stampPath = join(here, "build-info.json");
	try {
		const raw = JSON.parse(readFileSync(stampPath, "utf8"));
		const stamp: { gitCommit?: string; buildTime?: number } = {};
		if (raw && typeof raw === "object") {
			if (typeof (raw as { gitCommit?: unknown }).gitCommit === "string") {
				stamp.gitCommit = (raw as { gitCommit: string }).gitCommit;
			}
			if (typeof (raw as { buildTime?: unknown }).buildTime === "number") {
				stamp.buildTime = (raw as { buildTime: number }).buildTime;
			}
		}
		cachedStamp = stamp;
		return stamp;
	} catch {
		cachedStamp = {};
		return cachedStamp;
	}
}

/** Resolve the git commit the dist was built from. NEVER runs `git` at runtime.
 *  Precedence: build stamp (dist/build-info.json) → PI_TASKFLOW_BUILD_COMMIT
 *  env → "unknown". */
export function gitCommit(): string {
	const stamp = readBuildStamp();
	if (stamp.gitCommit) return stamp.gitCommit;
	const env = process.env.PI_TASKFLOW_BUILD_COMMIT;
	if (typeof env === "string" && env.trim()) return env.trim();
	return UNKNOWN_BUILD_COMMIT;
}

/** The build timestamp (ms epoch) the dist was stamped at, if known. */
export function buildTime(): number | undefined {
	return readBuildStamp().buildTime;
}

/** The full build-info record. Host adapters stamp RunState + report this to
 *  `action=version` / `taskflow_version`. */
export function getBuildInfo(): BuildInfo {
	const stampedBuildTime = buildTime();
	return {
		packageVersion: packageVersion(),
		gitCommit: gitCommit(),
		schemaVersion: CURRENT_RUN_STATE_SCHEMA_VERSION,
		...(stampedBuildTime !== undefined ? { buildTime: stampedBuildTime } : {}),
	};
}
