// AUTO-GENERATED by scripts/gen-versions.mjs from vendor.manifest.json — do not edit by hand.
// Regenerate with: bun run generate:versions  (or node ./scripts/gen-versions.mjs)
//
// Single source of truth: vendor.manifest.json at the repo root. The
// generated file is committed so the published tarball stays hermetic
// (vendor.manifest.json is not part of the npm package).
export const HARNESS_VERSIONS: Readonly<Record<string, string>> = {
	"@runecraft/goal-loop-audit": "0.28.34",
	"@runecraft/pr-review": "1.11.4",
	"@runecraft/subagents": "0.37.2",
	"@runecraft/taskflow": "0.2.6",
	"@runecraft/taskflow-core": "0.2.6",
	"@runecraft/taskflow-dsl": "0.2.6",
};
