// AUTO-GENERATED by scripts/gen-versions.mjs from the committed fork package.json files — do not edit by hand.
// Regenerate with: bun run generate:versions  (or node ./scripts/gen-versions.mjs)
//
// Single source of truth: the 12 committed fork packages
// (packages/{subagents,taskflow/*,goal-loop-audit,pr-review}/package.json). The
// generated file is committed so the published tarball stays hermetic (the
// fork package.json files are not part of the npm package).
export const HARNESS_VERSIONS: Readonly<Record<string, string>> = {
	"@runecraft/goal-loop-audit": "0.28.34",
	"@runecraft/pr-review": "1.11.4",
	"@runecraft/subagents": "0.37.2",
	"@runecraft/taskflow": "0.2.6",
	"@runecraft/taskflow-claude": "0.2.6",
	"@runecraft/taskflow-codex": "0.2.6",
	"@runecraft/taskflow-core": "0.2.6",
	"@runecraft/taskflow-dsl": "0.2.6",
	"@runecraft/taskflow-grok": "0.2.6",
	"@runecraft/taskflow-hosts": "0.2.6",
	"@runecraft/taskflow-mcp-core": "0.2.6",
	"@runecraft/taskflow-opencode": "0.2.6",
};
